apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test"
  description: "asd"
  annotations:
    github.com/project-slug: zsutton/testtest
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: "team-a"
